# Etapa 1: Builder
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Instalar herramientas necesarias para build
RUN apk add --no-cache git build-base ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/app
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -extldflags '-static'" -o /app/main


FROM alpine:latest

WORKDIR /root/

# Instalar tzdata
RUN apk add --no-cache tzdata

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
